# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71343bfaeb67ec092694da1ae7d39944f725bd20b45ddf1f824b2e9fe907657ded5e10ee0b1c0dcefe8462fe26ab84e96fb7c5d9dbfed6b037b234543c70421f

test:
  secret_key_base: ec208431d42cd8b8b0c6d48e95a4c1ae968efa4af1920b95d87a660849997f0b5eb85631c4537bc369d87d16a44ae77d9f473b5f619d158cafcde3ac4bbbfa15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
